In [1]:
import torch
from torch_geometric.data import Data
from torch_geometric import seed_everything
import pandas as pd
from sklearn.preprocessing import KBinsDiscretizer
import torch_geometric
from tqdm import tqdm, trange
from torcheval.metrics import MulticlassAccuracy
from torcheval.metrics import BinaryAUROC
import numpy as np

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# DEVICE = torch.device('cuda')
print(DEVICE)

/home/tsou/.conda/envs/pyg/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


cuda


In [2]:
# get feature from csv
# RAW_data = pd.read_csv('data/adult.csv')
# CAT = ['workclass','education','marital-status','occupation','relationship','race','gender','native-country']
# NUM = ['age','fnlwgt','educational-num','capital-gain','capital-loss','hours-per-week']
# LABEL = 'income'
RAW_data = pd.read_csv('data/compass_old.csv')
CAT=['sex','age_cat','race','c_charge_degree','decile_score.1','score_text','v_type_of_assessment','v_decile_score','v_score_text']
NUM=['age','juv_fel_count','juv_misd_count','juv_other_count','priors_count','days_b_screening_arrest','c_days_from_compas','end']
LABEL = 'is_recid'
# convert categorical data to ordinal data
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
data_pd = RAW_data.copy()
data_pd[CAT] = enc.fit_transform(RAW_data[CAT])
# data_pd = pd.get_dummies(RAW_data, columns=CAT, dtype=float)
# label to category
data_pd[LABEL] = data_pd[LABEL].astype('category').cat.codes

# realign data to num + cat
data_pd = data_pd[NUM + CAT + [LABEL]]

# caculate unique value of each categorical feature
cat_num = [len(data_pd[col].unique()) for col in CAT]

# normalize numerical data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
data_pd[NUM] = scaler.fit_transform(data_pd[NUM])

# convert data to tensor
x = torch.tensor(data_pd.drop(columns=[LABEL]).values, dtype=torch.float, device=DEVICE)  # [48842, 108]
y = torch.tensor(data_pd[LABEL].values, dtype=torch.long, device=DEVICE) # [48842]
print(x.shape, y.shape)
print(cat_num)
data_pd

torch.Size([16644, 17]) torch.Size([16644])
[2, 3, 6, 13, 10, 3, 1, 10, 3]


age  juv_fel_count  juv_misd_count  juv_other_count  priors_count  \
0     -0.763142       -0.17116       -0.195994        -0.249708     -0.769173   
1      0.277735       -0.17116       -0.195994        -0.249708     -0.399623   
2     -0.069224       -0.17116       -0.195994        -0.249708     -0.030074   
3      0.884913       -0.17116       -0.195994        -0.249708     -0.030074   
4     -0.849881       -0.17116       -0.195994         7.344876     -0.584398   
...         ...            ...             ...              ...           ...   
16639 -1.110101       -0.17116       -0.195994        -0.249708     -0.769173   
16640 -0.329443       -0.17116       -0.195994        -0.249708     -0.769173   
16641 -0.329443       -0.17116       -0.195994        -0.249708     -0.769173   
16642 -0.936621       -0.17116       -0.195994        -0.249708     -0.399623   
16643 -0.936621       -0.17116       -0.195994        -0.249708     -0.399623   

       days_b_screening_arrest  c_days_from_compas       end  sex  age_cat  \
0                    -0.067721           -0.155864  0.360236  1.0      0.0   
1                    -0.067721           -0.155864 -1.493342  0.0      0.0   
2                    -0.744908            0.051069  1.034535  1.0      0.0   
3                    -0.190846           -0.118240  0.366177  0.0      0.0   
4                    -0.350908           -0.069329  1.287026  0.0      2.0   
...                        ...                 ...       ...  ...      ...   
16639                -0.067721           -0.155864  1.319701  1.0      2.0   
16640                -0.067721           -0.155864 -0.245741  1.0      0.0   
16641                -0.067721           -0.155864  0.235476  1.0      0.0   
16642                -0.080033           -0.152102 -1.053711  0.0      2.0   
16643                -0.080033           -0.152102  0.083982  0.0      2.0   

       race  c_charge_degree  decile_score.1  score_text  \
0       0.0              3.0             3.0         1.0   
1       2.0              2.0             4.0         2.0   
2       2.0              6.0             5.0         2.0   
3       2.0              2.0             3.0         1.0   
4       2.0              7.0             3.0         1.0   
...     ...              ...             ...         ...   
16639   2.0              7.0             5.0         2.0   
16640   0.0              7.0             1.0         1.0   
16641   0.0              7.0             1.0         1.0   
16642   3.0              3.0             3.0         1.0   
16643   3.0              3.0             3.0         1.0   

       v_type_of_assessment  v_decile_score  v_score_text  is_recid  
0                       0.0             3.0           1.0         0  
1                       0.0             1.0           1.0         0  
2                       0.0             4.0           2.0         0  
3                       0.0             1.0           1.0         0  
4                       0.0             3.0           1.0         0  
...                     ...             ...           ...       ...  
16639                   0.0             6.0           2.0         1  
16640                   0.0             1.0           1.0         1  
16641                   0.0             1.0           1.0         1  
16642                   0.0             3.0           1.0         1  
16643                   0.0             3.0           1.0         1  

[16644 rows x 18 columns]

In [3]:
class feature_improtance_extractor():
    def __init__(self):
        self.feature_importance = []
        self.iter = 0
        pass
    def update(self, new_feature_importance):
        if self.iter == 0:
            self.feature_importance = new_feature_importance
        else:
            self.feature_importance += new_feature_importance
        self.iter += 1
        return
    
    def get(self):
        return (self.feature_importance / self.iter)
    
    def reset(self):
        self.feature_importance = []
        self.iter = 0
        return
extractor = feature_improtance_extractor()

In [21]:
class K_graph(torch.nn.Module):
    def __init__(self, NUM, CAT, LABEL, cat_num):
        super(K_graph, self).__init__()
        '''
        num_cols: number of numerical columns
        cat_cols: number of categorical columns
        label_cols: number of label columns
        cat_num: number of unique value of each categorical columns
        '''
        self.hidden_dim = 128
        # order: num -> cat -> label
        self.num_cols = len(NUM)
        self.cat_cols = len(CAT)
        self.label_cols = len(LABEL)
        self.number_of_columns = self.num_cols + self.cat_cols 
        self.K = round(self.number_of_columns*0.5)
        
        # numerical feature
        self.num_embeddings = torch.nn.ModuleList([torch.nn.Linear(1, self.hidden_dim) for i in range(self.num_cols)])
        # categorical feature
        self.cat_embeddings = torch.nn.ModuleList([torch.nn.Embedding(cat_num[i], self.hidden_dim) for i in range(self.cat_cols)])
        
        self.prediction = torch.nn.Sequential(
            torch.nn.Linear(self.hidden_dim *( self.K + self.number_of_columns), self.hidden_dim),
            torch.nn.ReLU(),
            torch.nn.LayerNorm(self.hidden_dim),
            torch.nn.Linear(self.hidden_dim, self.label_cols + 1)
        )
        
        # feature importance learning
        self.feature_importance_learners = torch.nn.Sequential(
            torch.nn.Linear(self.hidden_dim, self.hidden_dim),
            torch.nn.ReLU(),
            torch.nn.LayerNorm(self.hidden_dim),
            torch.nn.Dropout(p=0.5),
            torch.nn.Linear(self.hidden_dim, 1),
        ) 
        
        # graph convolution layers
        self.conv_GCN_input = torch_geometric.nn.GCNConv(self.number_of_columns*self.hidden_dim, self.hidden_dim)
        # self.conv_GCN_input = torch_geometric.nn.GCNConv(self.hidden_dim, self.hidden_dim)
        # self.conv_1_input = torch_geometric.nn.GATConv(self.number_of_columns*self.hidden_dim, self.hidden_dim)
        self.conv_GCN_2 = torch_geometric.nn.GCNConv(self.hidden_dim, self.hidden_dim)
        
        # self.transform = torch.nn.Linear(self.number_of_columns*self.hidden_dim, self.hidden_dim)
        
    def forward(self, input_data, epoch = -1):
        
        # make feature embedding
        num_data = input_data[:,:self.num_cols].unsqueeze(-1).unsqueeze(-1) 
        feature_embedding_num = torch.cat([self.num_embeddings[i](num_data[:,i]) for i in range(self.num_cols)], dim=1).reshape(len(input_data), -1) # [batch_size, num_cols * hidden_dim]
        feature_embedding_num = torch.nn.ReLU()(feature_embedding_num)
        feature_embedding_num = torch.layer_norm(feature_embedding_num, feature_embedding_num.shape)
        # categorical feature
        feature_embedding_cat = torch.cat([self.cat_embeddings[i](input_data[:,self.num_cols+i].long()) for i in range(self.cat_cols)], dim=1) # [batch_size, cat_cols * hidden_dim]
        feature_embedding_cat = torch.layer_norm(feature_embedding_cat, feature_embedding_cat.shape)
        # concat
        feature_embedding = torch.cat((feature_embedding_num, feature_embedding_cat), dim=1) # [batch_size, (num_cols + cat_cols) * hidden_dim]
        # feature_embedding = feature_embedding.reshape((len(input_data), self.number_of_columns, -1)) # [batch_size, (num_cols + cat_cols), hidden_dim]
        
        # feature importance learning
        feature_importance = torch.cat([self.feature_importance_learners(feature_embedding[:,i*self.hidden_dim:(i+1)*self.hidden_dim]) for i in range(self.number_of_columns)], dim=1) # [batch_size, num_cols + cat_cols, 1]
        # print(feature_importance)
        feature_importance = torch.layer_norm(feature_importance, feature_importance.shape)
        # feature_importance = torch.softmax(feature_importance, dim=1) # [batch_size, num_cols + cat_cols, 1]
        # print(feature_importance.shape)
        # print(feature_importance.sum(dim=1))
        # print(feature_importance)
        
        # weighted feature embedding 
        feature_embedding = feature_embedding.reshape((len(input_data),self.number_of_columns, -1)) * feature_importance.unsqueeze(-1) # [batch_size, (num_cols + cat_cols) * hidden_dim]
        feature_embedding = feature_embedding.reshape((len(input_data), -1)) # [batch_size, (num_cols + cat_cols) * hidden_dim]
        
        # top K feature importance
        K = self.K
        value, indices = torch.topk(feature_importance, K) # (value: [batch_size, k], indices: [batch_size, k])
        mask = torch.zeros_like(feature_importance, device=DEVICE)
        mask.scatter_(1, indices, 1)
        # importance_topK = torch.where(mask > 0, feature_importance, torch.zeros(feature_importance.shape,device=DEVICE)) # [batch_size, cols]
        importance_topK = torch.where(mask > 0, feature_importance, torch.empty(feature_importance.shape,device=DEVICE).fill_(-1e9)) # [batch_size, cols]
        importance_topK = torch.softmax(importance_topK, dim=1) # [batch_size, cols]
        # importance_topK = torch.stack([importance_topK.clone() for _ in range(self.number_of_columns)], dim=0) # [cols, batch_size, cols]
        
        extractor.update(feature_importance.sum(dim=0)/len(input_data))
        del feature_embedding_num, feature_embedding_cat, num_data
        del mask, feature_importance, value, indices
        
        
        processed_data = []
        processed_indices = []
        for target_col in range(self.number_of_columns):
            importance_topK_current = importance_topK.clone()# [batch_size, cols] 
            indices = importance_topK_current.T[target_col].nonzero().T[0] # selected samples' indices  
            
            if indices.shape[0] == 0:
                continue
            
            importance_topK_current = importance_topK_current[importance_topK_current.T[target_col]>0]# [????, cols]
            
            # for target column, set its importance to 0. so that it will not be fully connected graph
            # copy target column
            tmp = torch.clone(importance_topK_current[:,target_col]) # [????], save for future weighted sum
            importance_topK_current[:,target_col] = 0 # [????, cols]
            # multiply to get weighted adj
            weighted_adj = torch.matmul(importance_topK_current, importance_topK_current.T) # [batch_size, cols] * [cols, batch_size] = [batch_size, batch_size]
            # prune the diagonal
            weighted_adj = weighted_adj - torch.diag(weighted_adj.diagonal())

            # construct graph
            edge_index = weighted_adj.nonzero().T  # [2, num_edges]
            edge_wight = weighted_adj[edge_index[0], edge_index[1]] # [num_edges]
            edge_wight = torch.softmax(edge_wight, dim=0)

            
            if False:
                print('in graph', target_col, 'nodes:', len(indices), 'edges:', len(edge_wight),'ratio', len(edge_wight)/(len(indices)**2+0.000001))
            
            # print(edge_wight)
            # importance_topK_current[:,target_col] = tmp # [????, cols]
            
            features = (feature_embedding[indices]) # [????, cols*hidden_dim]
            # features = (feature_embedding.reshape(len(input_data),self.number_of_columns,-1)[indices][:,target_col,:]) # [????, hidden_dim]
            # print(features.shape)

            # construct graph 
            data = Data(x=features, edge_index=edge_index, edge_weight=edge_wight, indices=indices) 
            
            del features, edge_index, edge_wight, weighted_adj, importance_topK_current, tmp
            
            # apply GCN
            x = self.conv_GCN_input(data.x, data.edge_index, data.edge_weight)  # [???, hidden_dim]
            # x = self.conv_1_input(data.x, data.edge_index)  # [???, hidden_dim]
            x = torch.relu(x)
            x = torch.layer_norm(x, x.shape) # [???, hidden_dim]
            x = torch.nn.Dropout(p=0.5)(x)
            x = self.conv_GCN_2(x, data.edge_index, data.edge_weight)  # [???, hidden_dim]
            x = torch.relu(x)
            x = torch.layer_norm(x, x.shape)

            processed_data.append(x)
            processed_indices.append(indices)
        
        processed_data = torch.cat(processed_data, dim=0) 
        processed_indices = torch.cat(processed_indices, dim=0)
        # print(processed_indices)
        # print(processed_indices.argsort())
        # print(processed_indices[processed_indices.argsort()])
        processed_data = processed_data[processed_indices.argsort()] # ???????
        processed_data = torch.split(processed_data, self.K) # ?????????
        processed_data = torch.stack(list(processed_data), dim=0) # ???????????
        # processed_data = torch.sum(list(processed_data), dim=0) # ???????????

        # cat residual
        processed_data = torch.cat((processed_data, feature_embedding.reshape((len(input_data),self.number_of_columns,-1))), dim=1) # [batch_size, K+cols , hidden_dim]
        
        # make prediction
        prediction = self.prediction(processed_data.reshape(processed_data.shape[0],-1))
        # prediction = self.prediction(feature_embedding)
        
        
        return prediction


In [22]:
the_model = K_graph(NUM, CAT, [LABEL], cat_num).to(DEVICE)
optimizer = torch.optim.SGD(the_model.parameters(), lr=0.001)

# optimizer.step()
data_count = 5
# random pick data
indices = torch.randperm(len(x))[:data_count]
train_data = x[indices]
train_label = y[indices]

for i in range(5):
    
    optimizer.zero_grad()
    output = the_model(train_data[:data_count], epoch=200)
    loss = torch.nn.functional.cross_entropy(output, train_label[:data_count])
    loss.backward()
    # print(((the_model.feature_importance_learners.grad).abs().max(dim=1)[0]))
    optimizer.step()
    
    print('-----------------------------------------')


tensor([[0.0000, 0.0636],
        [0.0636, 0.0000]], device='cuda:0', grad_fn=<SubBackward0>)
tensor([[0.0000, 0.0364, 0.0268],
        [0.0364, 0.0000, 0.0643],
        [0.0268, 0.0643, 0.0000]], device='cuda:0', grad_fn=<SubBackward0>)
tensor([[0.0000, 0.0533, 0.0912, 0.0317, 0.0592],
        [0.0533, 0.0000, 0.0367, 0.0309, 0.0895],
        [0.0912, 0.0367, 0.0000, 0.0864, 0.0430],
        [0.0317, 0.0309, 0.0864, 0.0000, 0.0289],
        [0.0592, 0.0895, 0.0430, 0.0289, 0.0000]], device='cuda:0',
       grad_fn=<SubBackward0>)
tensor([[0.0000, 0.0363, 0.0942],
        [0.0363, 0.0000, 0.0860],
        [0.0942, 0.0860, 0.0000]], device='cuda:0', grad_fn=<SubBackward0>)
tensor([[0.]], device='cuda:0', grad_fn=<SubBackward0>)
tensor([[0.]], device='cuda:0', grad_fn=<SubBackward0>)
tensor([[0.0000, 0.0268, 0.0362],
        [0.0268, 0.0000, 0.0934],
        [0.0362, 0.0934, 0.0000]], device='cuda:0', grad_fn=<SubBackward0>)
tensor([[0.0000, 0.0987],
        [0.0987, 0.0000]], device='cu

In [6]:
import torchviz
plot = torchviz.make_dot(loss, params=dict(the_model.named_parameters()))
plot.render("MLP+FI", format="png")

'MLP+FI.png'

In [7]:

def train_epoch(model, optimizer, datas, batch_size, epoch):
    train_data, train_label, validation_data, validation_label = datas
    
    # slice data into batch
    train_data = torch.split(train_data, batch_size)
    train_label = torch.split(train_label, batch_size)
    validation_data = torch.split(validation_data, batch_size)
    validation_label = torch.split(validation_label, batch_size)

    # losses and metrics
    batch_loss = 0
    train_acc = MulticlassAccuracy(num_classes=2).to(DEVICE)
    train_auc = BinaryAUROC().to(DEVICE)
    valid_acc = MulticlassAccuracy(num_classes=2).to(DEVICE)
    valid_auc = BinaryAUROC().to(DEVICE)
    
    # train the model
    stepper = trange(len(train_data))
    for i in stepper:
        stepper.set_description(f'Epoch {epoch}')
        
        optimizer.zero_grad()
        output = model(train_data[i], epoch=epoch)
        loss = torch.nn.functional.cross_entropy(output, train_label[i]) * model.number_of_columns
        loss.backward()
        optimizer.step()
        batch_loss += loss.item()
        
        # metrics
        preds = output.softmax(dim=1)
        true = torch.nn.functional.one_hot(train_label[i], num_classes=2).to(DEVICE)
        train_acc.update(torch.argmax(preds, 1),true.T[1])
        train_auc.update(preds.T[0],true.T[0])
        
        # at the end of epoch, print result and validate the model
        if i == len(train_data) - 1:
            train_acc = train_acc.compute()
            train_auc = train_auc.compute()
            stepper.set_postfix({'loss': round(batch_loss/(i+1), 3), 'acc': round(train_acc.item(), 3), 'AUC': round(train_auc.item(), 3)})
            stepper.update()
        
            with torch.no_grad():
                for i in range(len(validation_data)):
                    output = model(validation_data[i], epoch=200)
                    # loss = torch.nn.functional.cross_entropy(output, validation_label[i])
                    preds = output.softmax(dim=1)
                    true = torch.nn.functional.one_hot(validation_label[i], num_classes=2).to(DEVICE)
                    valid_acc.update(torch.argmax(preds,1),true.T[1])
                    valid_auc.update(preds.T[0],true.T[0])
                stepper.set_postfix({'loss': round(batch_loss/(i+1), 3), 'acc': round(train_acc.item(), 3), 'AUC': round(train_auc.item(), 3), 'val_acc': round(valid_acc.compute().item(), 3), 'val_AUC': round(valid_auc.compute().item(), 3)})



In [8]:
def overall_train(x, y, seed=0):
    # hyperparameter
    epoch = 50
    batch_size = 1000
    seed_everything(seed)
    
    # shuffle data
    indices = torch.randperm(len(x))
    x = x[indices]
    y = y[indices]
    # slice data into train and test and validation
    train_ratio = 0.7
    validation_ratio = 0.1
    train_data = x[:int(len(x)*train_ratio)]
    train_label = y[:int(len(x)*train_ratio)]
    validation_data = x[int(len(x)*train_ratio):int(len(x)*(train_ratio+validation_ratio))]
    validation_label = y[int(len(x)*train_ratio):int(len(x)*(train_ratio+validation_ratio))]
    test_data = x[int(len(x)*(train_ratio+validation_ratio)):]
    test_label = y[int(len(x)*(train_ratio+validation_ratio)):]

    # build model and optimizer
    the_model = K_graph(NUM, CAT, [LABEL], cat_num).to(DEVICE)
    optimizer = torch.optim.SGD(the_model.parameters(), lr=0.001)
    
    # train the model
    datas = (train_data, train_label, validation_data, validation_label)
    for i in range(epoch):
        train_epoch(the_model, optimizer, datas, batch_size, epoch=i+1)
        print(extractor.get())
        extractor.reset()
    
    # test the model
    with torch.no_grad():
        test_data = torch.split(test_data, batch_size)
        test_label = torch.split(test_label, batch_size)
        for i in range(len(test_data)):
            output = the_model(test_data[i], epoch=200)
            preds = output.softmax(dim=1)
            true = torch.nn.functional.one_hot(test_label[i], num_classes=2).to(DEVICE)
            test_acc = MulticlassAccuracy(num_classes=2).to(DEVICE)
            test_auc = BinaryAUROC().to(DEVICE)
            test_acc.update(torch.argmax(preds,1),true.T[1])
            test_auc.update(preds.T[0],true.T[0])

        print('test_acc:', test_acc.compute().item())
        print('test_auc:', test_auc.compute().item())
        print('-----------------------------------------')

In [14]:
seed_set = [9,90,900,9000,90000]
overall_train(x, y, seed=9)

Epoch 1:   0%|          | 0/12 [00:00<?, ?it/s]

Epoch 1: 100%|██████████| 12/12 [00:03<00:00,  3.63it/s, loss=74.9, acc=0.593, AUC=0.62, val_acc=0.658, val_AUC=0.712]


tensor([ 0.0910, -0.2222, -0.3857,  0.0628,  0.3273, -0.0124,  0.0954, -0.8044,
         0.1037,  0.4230,  0.2478,  0.3863, -0.0551,  0.1489,  0.0644,  0.1103,
        -0.5810], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 2: 100%|██████████| 12/12 [00:03<00:00,  3.63it/s, loss=64, acc=0.657, AUC=0.709, val_acc=0.669, val_AUC=0.728]


tensor([ 0.1120, -0.4597, -0.3330,  0.1018,  0.8076, -0.2562,  0.2192, -1.0856,
        -0.1338,  0.2776,  0.3291,  0.5850,  0.0904,  0.2498,  0.1983,  0.2154,
        -0.9181], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 3: 100%|██████████| 12/12 [00:03<00:00,  3.60it/s, loss=62.9, acc=0.665, AUC=0.723, val_acc=0.674, val_AUC=0.729]


tensor([ 0.0410, -0.5782, -0.3178,  0.0781,  1.0028, -0.3138,  0.3415, -1.2122,
        -0.1296,  0.2900,  0.3395,  0.5836,  0.0958,  0.2608,  0.2855,  0.2366,
        -1.0036], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 4: 100%|██████████| 12/12 [00:03<00:00,  3.60it/s, loss=62, acc=0.678, AUC=0.734, val_acc=0.687, val_AUC=0.736]


tensor([ 0.0269, -0.6693, -0.3060,  0.0470,  1.1691, -0.3219,  0.3044, -1.2246,
        -0.1671,  0.3052,  0.3474,  0.5829,  0.1107,  0.2341,  0.3496,  0.2562,
        -1.0447], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 5: 100%|██████████| 12/12 [00:03<00:00,  3.59it/s, loss=62, acc=0.677, AUC=0.733, val_acc=0.694, val_AUC=0.75]


tensor([ 0.0256, -0.7456, -0.3209, -0.0139,  1.3084, -0.3479,  0.3099, -1.1991,
        -0.1691,  0.2990,  0.3737,  0.6115,  0.1223,  0.2092,  0.3086,  0.2781,
        -1.0499], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 6: 100%|██████████| 12/12 [00:03<00:00,  3.59it/s, loss=61.1, acc=0.685, AUC=0.743, val_acc=0.684, val_AUC=0.751]


tensor([ 0.0403, -0.8373, -0.2922, -0.0361,  1.4152, -0.3776,  0.3008, -1.2062,
        -0.1747,  0.2754,  0.3812,  0.6357,  0.1461,  0.1878,  0.3119,  0.2670,
        -1.0373], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 7: 100%|██████████| 12/12 [00:03<00:00,  3.59it/s, loss=61.2, acc=0.682, AUC=0.742, val_acc=0.695, val_AUC=0.756]


tensor([ 0.0594, -0.8881, -0.2717, -0.0358,  1.4820, -0.3556,  0.3187, -1.2052,
        -0.2270,  0.2935,  0.4004,  0.6106,  0.1477,  0.1977,  0.2643,  0.2796,
        -1.0704], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 8: 100%|██████████| 12/12 [00:03<00:00,  3.58it/s, loss=60.8, acc=0.685, AUC=0.745, val_acc=0.688, val_AUC=0.744]


tensor([ 0.0500, -0.9038, -0.2143, -0.0355,  1.5406, -0.3559,  0.2758, -1.2127,
        -0.2535,  0.2849,  0.3936,  0.6044,  0.1414,  0.1961,  0.2834,  0.2794,
        -1.0738], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 9: 100%|██████████| 12/12 [00:03<00:00,  3.58it/s, loss=60.7, acc=0.689, AUC=0.748, val_acc=0.686, val_AUC=0.753]


tensor([ 0.0653, -0.9258, -0.2092, -0.0664,  1.5947, -0.3933,  0.2644, -1.2144,
        -0.2400,  0.3023,  0.3918,  0.5833,  0.1434,  0.2254,  0.2800,  0.2734,
        -1.0750], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 10: 100%|██████████| 12/12 [00:03<00:00,  3.57it/s, loss=60.6, acc=0.692, AUC=0.749, val_acc=0.695, val_AUC=0.755]


tensor([ 0.0703, -0.9457, -0.2420, -0.0640,  1.6420, -0.4096,  0.2266, -1.1742,
        -0.2415,  0.2821,  0.3765,  0.5656,  0.1579,  0.2573,  0.2861,  0.2847,
        -1.0720], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 11: 100%|██████████| 12/12 [00:03<00:00,  3.58it/s, loss=60.6, acc=0.691, AUC=0.749, val_acc=0.686, val_AUC=0.753]


tensor([ 0.0859, -0.9707, -0.2461, -0.0498,  1.6612, -0.4279,  0.2050, -1.1613,
        -0.2445,  0.2863,  0.3642,  0.5465,  0.1615,  0.2774,  0.2799,  0.2897,
        -1.0572], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 12: 100%|██████████| 12/12 [00:03<00:00,  3.58it/s, loss=60.5, acc=0.688, AUC=0.75, val_acc=0.696, val_AUC=0.756]


tensor([ 0.0841, -0.9647, -0.2376, -0.0362,  1.6993, -0.4652,  0.1627, -1.1259,
        -0.2453,  0.2967,  0.3683,  0.5098,  0.1664,  0.2963,  0.2703,  0.2926,
        -1.0715], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 13: 100%|██████████| 12/12 [00:03<00:00,  3.58it/s, loss=60.1, acc=0.694, AUC=0.754, val_acc=0.701, val_AUC=0.758]


tensor([ 0.0954, -0.9673, -0.2177, -0.0435,  1.7140, -0.4785,  0.1368, -1.1312,
        -0.2647,  0.2910,  0.3712,  0.5119,  0.1623,  0.2969,  0.2818,  0.3044,
        -1.0628], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 14: 100%|██████████| 12/12 [00:03<00:00,  3.58it/s, loss=60.2, acc=0.693, AUC=0.752, val_acc=0.687, val_AUC=0.753]


tensor([ 0.0910, -0.9546, -0.2291, -0.0145,  1.7177, -0.4867,  0.1261, -1.1447,
        -0.3062,  0.3100,  0.3782,  0.5077,  0.1453,  0.3038,  0.3030,  0.2990,
        -1.0460], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 15: 100%|██████████| 12/12 [00:03<00:00,  3.58it/s, loss=60.1, acc=0.692, AUC=0.754, val_acc=0.687, val_AUC=0.761]


tensor([ 0.1119, -0.9488, -0.2158, -0.0060,  1.7407, -0.4974,  0.1036, -1.1195,
        -0.3312,  0.3095,  0.3652,  0.5024,  0.1530,  0.2977,  0.2754,  0.3039,
        -1.0447], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 16: 100%|██████████| 12/12 [00:03<00:00,  3.59it/s, loss=59.8, acc=0.694, AUC=0.758, val_acc=0.69, val_AUC=0.76]


tensor([ 0.1160, -0.9114, -0.1994, -0.0023,  1.7682, -0.5049,  0.0473, -1.1137,
        -0.3339,  0.3046,  0.3546,  0.4878,  0.1422,  0.2923,  0.2756,  0.3108,
        -1.0338], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 17: 100%|██████████| 12/12 [00:03<00:00,  3.59it/s, loss=59.8, acc=0.697, AUC=0.757, val_acc=0.692, val_AUC=0.756]


tensor([ 0.1370, -0.8913, -0.1846, -0.0057,  1.7827, -0.5133,  0.0090, -1.1098,
        -0.3689,  0.2959,  0.3480,  0.4895,  0.1426,  0.2981,  0.2904,  0.3020,
        -1.0219], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 18: 100%|██████████| 12/12 [00:03<00:00,  3.59it/s, loss=59.7, acc=0.694, AUC=0.759, val_acc=0.704, val_AUC=0.763]


tensor([ 0.1528, -0.9073, -0.1919, -0.0039,  1.7942, -0.4961, -0.0197, -1.1007,
        -0.3884,  0.3007,  0.3434,  0.4970,  0.1451,  0.2839,  0.2962,  0.3065,
        -1.0119], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 19: 100%|██████████| 12/12 [00:03<00:00,  3.59it/s, loss=59.7, acc=0.696, AUC=0.758, val_acc=0.702, val_AUC=0.761]


tensor([ 0.1708, -0.9114, -0.1876,  0.0074,  1.7998, -0.5092, -0.0251, -1.1034,
        -0.4283,  0.3134,  0.3605,  0.4725,  0.1393,  0.2952,  0.2972,  0.2986,
        -0.9896], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 20: 100%|██████████| 12/12 [00:03<00:00,  3.60it/s, loss=59.6, acc=0.699, AUC=0.76, val_acc=0.708, val_AUC=0.765]


tensor([ 0.1803, -0.8929, -0.1982, -0.0196,  1.8299, -0.5116, -0.0253, -1.0988,
        -0.4232,  0.3219,  0.3527,  0.4641,  0.1392,  0.3030,  0.2691,  0.2950,
        -0.9857], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 21: 100%|██████████| 12/12 [00:03<00:00,  3.60it/s, loss=59.5, acc=0.698, AUC=0.761, val_acc=0.707, val_AUC=0.765]


tensor([ 0.1890, -0.9098, -0.1914, -0.0248,  1.8283, -0.5153, -0.0364, -1.0752,
        -0.4097,  0.3277,  0.3576,  0.4622,  0.1312,  0.3049,  0.2586,  0.2905,
        -0.9875], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 22: 100%|██████████| 12/12 [00:03<00:00,  3.59it/s, loss=59.3, acc=0.698, AUC=0.763, val_acc=0.694, val_AUC=0.758]


tensor([ 0.2028, -0.9038, -0.1751, -0.0219,  1.8351, -0.5239, -0.0564, -1.0581,
        -0.4287,  0.3284,  0.3471,  0.4808,  0.1331,  0.3003,  0.2409,  0.2884,
        -0.9888], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 23: 100%|██████████| 12/12 [00:03<00:00,  3.60it/s, loss=59.3, acc=0.699, AUC=0.762, val_acc=0.703, val_AUC=0.771]


tensor([ 0.2007, -0.9061, -0.1706, -0.0248,  1.8404, -0.5264, -0.0687, -1.0558,
        -0.4356,  0.3251,  0.3587,  0.4773,  0.1335,  0.2997,  0.2360,  0.2954,
        -0.9789], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 24: 100%|██████████| 12/12 [00:03<00:00,  3.59it/s, loss=59.3, acc=0.698, AUC=0.763, val_acc=0.71, val_AUC=0.766]


tensor([ 0.1912, -0.9273, -0.1588, -0.0104,  1.8425, -0.5031, -0.0596, -1.0579,
        -0.4394,  0.3380,  0.3792,  0.4551,  0.1201,  0.3028,  0.2252,  0.2863,
        -0.9839], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 25: 100%|██████████| 12/12 [00:03<00:00,  3.59it/s, loss=59.2, acc=0.704, AUC=0.763, val_acc=0.709, val_AUC=0.765]


tensor([ 0.1922, -0.9120, -0.1560, -0.0131,  1.8444, -0.4860, -0.0975, -1.0676,
        -0.4347,  0.3604,  0.3860,  0.4611,  0.1160,  0.3024,  0.2166,  0.2736,
        -0.9858], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 26: 100%|██████████| 12/12 [00:03<00:00,  3.59it/s, loss=59, acc=0.696, AUC=0.765, val_acc=0.705, val_AUC=0.764]


tensor([ 0.2041, -0.9151, -0.1639, -0.0113,  1.8495, -0.4833, -0.1082, -1.0678,
        -0.4299,  0.3609,  0.3865,  0.4592,  0.1083,  0.3141,  0.2145,  0.2673,
        -0.9850], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 27: 100%|██████████| 12/12 [00:03<00:00,  3.55it/s, loss=59.1, acc=0.699, AUC=0.765, val_acc=0.703, val_AUC=0.761]


tensor([ 0.1967, -0.8917, -0.1539, -0.0191,  1.8491, -0.4954, -0.0956, -1.0813,
        -0.4226,  0.3598,  0.3875,  0.4434,  0.1128,  0.3209,  0.2118,  0.2609,
        -0.9833], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 28: 100%|██████████| 12/12 [00:03<00:00,  3.59it/s, loss=59.1, acc=0.701, AUC=0.764, val_acc=0.703, val_AUC=0.763]


tensor([ 1.9830e-01, -8.6992e-01, -1.6056e-01, -9.4425e-04,  1.8576e+00,
        -5.0440e-01, -1.0998e-01, -1.0759e+00, -4.2374e-01,  3.5881e-01,
         3.8260e-01,  4.3097e-01,  1.0913e-01,  3.3727e-01,  2.0217e-01,
         2.5190e-01, -9.8335e-01], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 29: 100%|██████████| 12/12 [00:03<00:00,  3.60it/s, loss=59, acc=0.703, AUC=0.766, val_acc=0.701, val_AUC=0.766]


tensor([ 0.1995, -0.8756, -0.1487, -0.0024,  1.8477, -0.4912, -0.1208, -1.0809,
        -0.4267,  0.3588,  0.4086,  0.4289,  0.1032,  0.3243,  0.2048,  0.2473,
        -0.9769], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 30: 100%|██████████| 12/12 [00:03<00:00,  3.60it/s, loss=58.9, acc=0.702, AUC=0.767, val_acc=0.7, val_AUC=0.765]


tensor([ 0.1849, -0.8710, -0.1534, -0.0181,  1.8499, -0.5050, -0.1362, -1.0635,
        -0.4287,  0.3755,  0.4072,  0.4289,  0.1029,  0.3240,  0.2235,  0.2557,
        -0.9766], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 31: 100%|██████████| 12/12 [00:03<00:00,  3.60it/s, loss=59, acc=0.7, AUC=0.765, val_acc=0.706, val_AUC=0.77]


tensor([ 0.1742, -0.8785, -0.1494,  0.0019,  1.8399, -0.5128, -0.1384, -1.0574,
        -0.4589,  0.3846,  0.4220,  0.4203,  0.1062,  0.3329,  0.2369,  0.2454,
        -0.9689], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 32: 100%|██████████| 12/12 [00:03<00:00,  3.60it/s, loss=58.7, acc=0.704, AUC=0.769, val_acc=0.706, val_AUC=0.768]


tensor([ 0.1792, -0.8762, -0.1497,  0.0235,  1.8280, -0.4978, -0.1357, -1.0511,
        -0.4855,  0.3834,  0.4371,  0.4140,  0.0980,  0.3252,  0.2302,  0.2441,
        -0.9666], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 33: 100%|██████████| 12/12 [00:03<00:00,  3.60it/s, loss=58.4, acc=0.704, AUC=0.772, val_acc=0.705, val_AUC=0.771]


tensor([ 0.1964, -0.8819, -0.1597,  0.0154,  1.8485, -0.4899, -0.1551, -1.0476,
        -0.4759,  0.3822,  0.4594,  0.4069,  0.0880,  0.3146,  0.2246,  0.2409,
        -0.9666], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 34: 100%|██████████| 12/12 [00:03<00:00,  3.60it/s, loss=58.5, acc=0.706, AUC=0.77, val_acc=0.712, val_AUC=0.768]


tensor([ 0.1975, -0.8806, -0.1460,  0.0179,  1.8319, -0.4917, -0.1680, -1.0367,
        -0.4929,  0.3933,  0.4569,  0.4116,  0.0909,  0.3075,  0.2184,  0.2470,
        -0.9570], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 35: 100%|██████████| 12/12 [00:03<00:00,  3.61it/s, loss=58.6, acc=0.704, AUC=0.77, val_acc=0.704, val_AUC=0.764]


tensor([ 0.1783, -0.8611, -0.1384,  0.0207,  1.8338, -0.4796, -0.1821, -1.0509,
        -0.4998,  0.3924,  0.4774,  0.4042,  0.0891,  0.3133,  0.2103,  0.2440,
        -0.9516], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 36: 100%|██████████| 12/12 [00:03<00:00,  3.60it/s, loss=58.4, acc=0.705, AUC=0.771, val_acc=0.707, val_AUC=0.772]


tensor([ 0.1845, -0.8471, -0.1357,  0.0192,  1.8270, -0.4695, -0.1893, -1.0605,
        -0.5087,  0.3879,  0.4937,  0.3946,  0.0845,  0.3274,  0.2042,  0.2412,
        -0.9535], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 37: 100%|██████████| 12/12 [00:03<00:00,  3.60it/s, loss=58.6, acc=0.703, AUC=0.769, val_acc=0.706, val_AUC=0.769]


tensor([ 0.1872, -0.8480, -0.1444,  0.0124,  1.8251, -0.4691, -0.1902, -1.0668,
        -0.5127,  0.3824,  0.4920,  0.4101,  0.0872,  0.3192,  0.2094,  0.2484,
        -0.9422], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 38: 100%|██████████| 12/12 [00:03<00:00,  3.61it/s, loss=58.4, acc=0.704, AUC=0.772, val_acc=0.701, val_AUC=0.776]


tensor([ 0.1912, -0.8342, -0.1450,  0.0197,  1.8098, -0.4592, -0.1635, -1.0736,
        -0.5343,  0.3784,  0.5198,  0.4213,  0.0755,  0.3124,  0.1888,  0.2389,
        -0.9458], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 39: 100%|██████████| 12/12 [00:03<00:00,  3.61it/s, loss=58.2, acc=0.707, AUC=0.773, val_acc=0.705, val_AUC=0.765]


tensor([ 0.1702, -0.8145, -0.1462,  0.0276,  1.8015, -0.4730, -0.1586, -1.0672,
        -0.5494,  0.3798,  0.5405,  0.4072,  0.0701,  0.3292,  0.1822,  0.2323,
        -0.9317], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 40: 100%|██████████| 12/12 [00:03<00:00,  3.61it/s, loss=58.3, acc=0.701, AUC=0.772, val_acc=0.712, val_AUC=0.776]


tensor([ 0.1734, -0.8260, -0.1594,  0.0191,  1.7950, -0.4636, -0.1745, -1.0507,
        -0.5529,  0.3880,  0.5530,  0.4055,  0.0705,  0.3338,  0.1719,  0.2368,
        -0.9199], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 41: 100%|██████████| 12/12 [00:03<00:00,  3.61it/s, loss=58.1, acc=0.707, AUC=0.774, val_acc=0.709, val_AUC=0.767]


tensor([ 0.1721, -0.8296, -0.1576,  0.0145,  1.7858, -0.4667, -0.2203, -1.0374,
        -0.5613,  0.3969,  0.5663,  0.4053,  0.0790,  0.3460,  0.1697,  0.2450,
        -0.9078], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 42: 100%|██████████| 12/12 [00:03<00:00,  3.61it/s, loss=58.1, acc=0.709, AUC=0.775, val_acc=0.709, val_AUC=0.772]


tensor([ 0.1783, -0.8222, -0.1554,  0.0227,  1.7639, -0.4675, -0.2313, -1.0704,
        -0.5497,  0.3981,  0.5715,  0.4131,  0.0705,  0.3423,  0.1865,  0.2464,
        -0.8967], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 43: 100%|██████████| 12/12 [00:03<00:00,  3.61it/s, loss=57.9, acc=0.71, AUC=0.777, val_acc=0.703, val_AUC=0.771]


tensor([ 0.1891, -0.8202, -0.1553,  0.0281,  1.7696, -0.4556, -0.2357, -1.0769,
        -0.5388,  0.3994,  0.5820,  0.4027,  0.0628,  0.3317,  0.1889,  0.2319,
        -0.9036], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 44: 100%|██████████| 12/12 [00:03<00:00,  3.61it/s, loss=57.7, acc=0.709, AUC=0.778, val_acc=0.71, val_AUC=0.768]


tensor([ 0.1931, -0.8174, -0.1624,  0.0249,  1.7683, -0.4489, -0.2583, -1.0713,
        -0.5507,  0.4046,  0.5837,  0.4113,  0.0622,  0.3277,  0.1928,  0.2428,
        -0.9024], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 45: 100%|██████████| 12/12 [00:03<00:00,  3.61it/s, loss=57.7, acc=0.713, AUC=0.779, val_acc=0.692, val_AUC=0.768]


tensor([ 0.1898, -0.8123, -0.1564,  0.0204,  1.7676, -0.4457, -0.2621, -1.0737,
        -0.5445,  0.4063,  0.6003,  0.4031,  0.0558,  0.3378,  0.1834,  0.2261,
        -0.8959], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 46: 100%|██████████| 12/12 [00:03<00:00,  3.62it/s, loss=57.8, acc=0.709, AUC=0.777, val_acc=0.714, val_AUC=0.773]


tensor([ 0.1986, -0.8128, -0.1618,  0.0308,  1.7681, -0.4584, -0.2747, -1.0681,
        -0.5308,  0.4019,  0.6133,  0.3939,  0.0482,  0.3261,  0.1848,  0.2262,
        -0.8854], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 47: 100%|██████████| 12/12 [00:03<00:00,  3.61it/s, loss=57.7, acc=0.711, AUC=0.779, val_acc=0.705, val_AUC=0.769]


tensor([ 0.1927, -0.8098, -0.1750,  0.0417,  1.7592, -0.4476, -0.2869, -1.0703,
        -0.5441,  0.4097,  0.6208,  0.3881,  0.0483,  0.3221,  0.2009,  0.2292,
        -0.8792], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 48: 100%|██████████| 12/12 [00:03<00:00,  3.61it/s, loss=57.7, acc=0.709, AUC=0.779, val_acc=0.712, val_AUC=0.78]


tensor([ 0.1954, -0.8043, -0.1846,  0.0387,  1.7375, -0.4665, -0.2932, -1.0431,
        -0.5464,  0.4019,  0.6375,  0.3966,  0.0518,  0.3247,  0.2073,  0.2274,
        -0.8807], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 49: 100%|██████████| 12/12 [00:03<00:00,  3.61it/s, loss=57.7, acc=0.709, AUC=0.779, val_acc=0.702, val_AUC=0.769]


tensor([ 0.2019, -0.8125, -0.1797,  0.0366,  1.7382, -0.4702, -0.3154, -1.0306,
        -0.5427,  0.4064,  0.6408,  0.3956,  0.0442,  0.3377,  0.2059,  0.2267,
        -0.8830], device='cuda:0', grad_fn=<DivBackward0>)


Epoch 50: 100%|██████████| 12/12 [00:03<00:00,  3.62it/s, loss=57.1, acc=0.713, AUC=0.784, val_acc=0.706, val_AUC=0.777]


tensor([ 0.1809, -0.7920, -0.1780,  0.0283,  1.7456, -0.4753, -0.3254, -1.0185,
        -0.5421,  0.4120,  0.6570,  0.3937,  0.0384,  0.3390,  0.1879,  0.2247,
        -0.8761], device='cuda:0', grad_fn=<DivBackward0>)
test_acc: 0.7051671743392944
test_auc: 0.7808573540280858
-----------------------------------------


In [15]:
sum([0.7051671743392944,
     0.7082067131996155,
     0.7051671743392944,
     0.7264437675476074,
     0.7325227856636047
     ])/5

0.7155015230178833

In [16]:
sum([0.7808573540280858,
     0.7863905325443787,
     0.7797353553374963,
     0.8075237670825907,
     0.8157019294743846
     ])/5

0.7940417876933872